---
- hosts: all
  become: yes
  tasks:
    - name: Install latest version of apache
      apt:
        name: apache2
        state: latest
    - name: Start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Create index.html
      file:
        path: /var/www/html/index.html
        state: touch
    - name: Add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "Hello World! Chandra Sekhar"
      register: var
    - name: Output debug info
      debug: msg="debug info is {{ var }}"
