---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: check if the apache is in stopped state
      systemd:
        name: apache2
      register: output
    - name: start apache
      service:
        name: apache2
        state: started
      when:
        - output.status.SubState == "dead"
    - name: debug info
      debug: msg="Register output is {{ output.status.SubState }}"
